Csi 1167 handle device upgrade errors
Cypherock/cysync-module-communication pull request #16
Opened 2022-07-18 12:33 UTC by HarishRocks

2022-07-19 13:40 UTC, irshadCypherock requested changes

2022-07-19 13:40 UTC, irshadCypherock commented on src/errors/index.ts
> +  FLASH_NACK = 'HD_FIRM_1011',
We are not using this error anywhere?

2022-07-20 05:14 UTC, HarishRocks commented on src/core/operations/stmSendData.ts
> +    errorObj: DeviceErrorType.FLASH_NACK
Nice catch! It should have been used here before

2022-08-01 07:23 UTC, irshadCypherock approved these changes

2022-08-01 07:24 UTC, merged