Device communication rewrite with global listeners
Cypherock/cysync-module-communication pull request #3
Opened 2022-04-14 16:38 UTC by irshadCypherock

2022-04-14 16:42 UTC, irshadCypherock commented
Task linked: [CSI-942 Rewrite communication module with Global listeners](https://app.clickup.com/t/37308523/CSI-942)

2022-04-23 00:04 UTC, Suraj-Tiwari requested changes
there are many code consistencies too, using one pattern in certain sections and another in other section ts-doc comments is a plus

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +  private async processPacket(
1 - if not open L119, this promise will never resolve or reject. 
2 - Line 121, after broadcast it won't resolve/reject either. 
3 - Don't do nested if else, try this:
```js
if(!this.isOpen()) {
   return _reject();
}
if (this.isInfoPacket(newPacket)) {
    this.broadcastPacket(newPacket);
    return resolve();
 } 
if (newPacket.errorList.length <= 0){
   // return resolve/reject
} else {
   // return resolve/reject
}
```
 4 - don't ignore rejection, let caller ignore it if they want but return something, complete execution cycle with proper acknowledge response .

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +        logger.info(`Checking if packet version ${version} works`);
don't pollute logs, record only success and rejection.

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +  private checkPacketVersion(version: PacketVersion) {
if error is somehow null, it'll become same, an unfinished promise.

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +    const packets: PacketData[] = [];
can't we do 🤔
```js
return this.poolData.filter((x) => commandTypes.includes(x.commandType));
```

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +    return this.runOperation(() => {
why?

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +    return this.runOperation(() => {
why? again!

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/index.ts
> +    return this.runOperation(() => {
😕

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/base.ts
> +            reject(error);
you can simply return reject, will look cleaner.

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/deviceConnection/base.ts
> +   * Run this function before starting every operation on the device.
if this (beforeOperation/afterOperation) is a must, handle it in automated way if possible. There are many things which can go wrong if someone just forgot to call either of them,

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/connection.ts
> +  } else {
no need to put else, throw acts as a return. Try to avoid unnecessary checks & conditions.

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/connection.ts
> +
formatting!

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/receiveData.ts
> +  _version: PacketVersion,
it's if here just to keep backward compatibility, it's already broken, data type changes.

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/receiveData.ts
> +        reject(new DeviceError(DeviceErrorType.NOT_CONNECTED));
return reject, more consistent with other code

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/receiveData.ts
> +              logger.info(
log errors only,

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/sendData.ts
> +      if (ePacket.commandType === usableCommands.ACK_PACKET) {
use switch and return

2022-04-23 00:04 UTC, Suraj-Tiwari commented on src/core/stmSendData.ts
>          resolve(undefined);
default is undefined anyway

2022-04-27 10:06 UTC, irshadCypherock commented on src/core/deviceConnection/base.ts
> +   * Run this function before starting every operation on the device.
The `beforeOperation` and `afterOperation` are to be used for before and after each flow. That is `addCoin`, `addWallet` etc.

Since these flows contains multiple send and receive calls, I couldn't find a way to implement it inside the `DeviceConnection` itself.

One way I can think of is to automatically open the port when any operation is performed and then close the port after some interval. I had implemented this while working on this POC but later discarded it because the closing of port is also used as a method to abort the flow. 

For example: If the `addCoin` flow is in execution, and the flow is like.
```
1. sendData(21)
2. receiveData(22)
3. sendData(23)
4. receiveData(24)
````
If suppose the flow execution is on step 2 and it's waiting for the device to receive some data. To abort this execution from outside, what we do is close the connection port and the internal listener of `receiveData` handles this as an error and the whole `addCoin` flow results in an error due to this abort.

2022-04-27 10:14 UTC, irshadCypherock commented on src/core/stmSendData.ts
>          resolve(undefined);
If we change the `resolve(undefined)` to `resolve()` then we need to change the return type from `Promise<string | undefined>` to `Promise<string | void>`.

![image](https://user-images.githubusercontent.com/80461749/165495996-1d003957-8926-4b1c-b7c5-215e21f11db0.png)

2022-05-02 01:43 UTC, Suraj-Tiwari requested changes
Just One comment, merge it after fixing it.

2022-05-02 01:43 UTC, Suraj-Tiwari commented on src/core/stmSendData.ts
>              resolve(true);
keep it consistent `return resolve(true);`

2022-05-05 07:14 UTC, merged