feat: add support for arbitrum & optimism
Cypherock/cysync-module-communication pull request #38
Opened 2023-01-19 15:45 UTC by ujjwal-cyph

Fixes https://app.clickup.com/t/37308523/CSI-1584

2023-01-28 07:08 UTC, irshadCypherock commented
Task linked: [CU-85zrja2x6 Add support for Arbitrum & Optimism](https://app.clickup.com/t/85zrja2x6)

2023-01-28 07:12 UTC, irshadCypherock requested changes

2023-01-28 07:12 UTC, irshadCypherock commented on src/constants/coins/eth.ts
> +    oldId: 'eth',
Make the old Id optional

2023-01-28 07:36 UTC, ujjwal-cyph commented on src/constants/coins/eth.ts
> +    oldId: 'eth',
changed.

2023-01-28 10:23 UTC, irshadCypherock requested changes

2023-01-28 10:23 UTC, irshadCypherock commented on src/constants/types/AbsCoinData.ts
> +    this.oldId = oldId ?? '';
Is this necessary?

2023-01-30 08:42 UTC, ujjwal-cyph commented on src/constants/types/AbsCoinData.ts
> +    this.oldId = oldId ?? '';
no.

2023-01-30 08:42 UTC, ujjwal-cyph commented on src/constants/types/AbsCoinData.ts
> +    this.oldId = oldId ?? '';
```suggestion
    this.oldId = oldId;
```

2023-01-30 08:43 UTC, ujjwal-cyph commented on src/constants/types/AbsCoinData.ts
> +    this.oldId = oldId ?? '';
Removed

2023-01-31 08:34 UTC, irshadCypherock approved these changes

2023-01-31 08:35 UTC, merged